### ISSUE TITLE
Handle request passwords...

### ISSUE THREAD

**Issue by hellopatrick** [helloresolven/rested#15]
It is very annoying to have to re-enter passwords each time you open a past request.  Especially if you forget to re-enter it on first request attempt.

Current ideas for fixing:
1. Store passwords in Keychain (like OAuth tokens) for security.  Not portable.
2. Store alongside username in the actual request file for portability.  Not secure.
3. Don't store, just ask for the password on request open if username detected.

**Comment by popstr** [comment]
I would also like to see an improvement in password management. Any of these three suggestions sounds good to me.
I personally wouldn't mind saving the password in an unsecure text file.
