### ISSUE TITLE
Changing Method clears Body field

### ISSUE THREAD

**Issue by woodnathan** [helloresolven/rested#19]
When changing the HTTP Method, it clears the HTTP Body view
Could this behaviour be removed as it makes it inconvenient to use the same window for testing CRUD methods when the HTTP body is cleared

**Comment by hellopatrick** [comment]
I think this is a bug if you are using a custom HTTP body...

**Comment by woodnathan** [comment]
Steps to reproduce:
- Check "Use Custom HTTP Body"
- Enter text
- Uncheck "Use Custom HTTP Body"
- Change HTTP method using drop down

**Comment by hellopatrick** [comment]
Are you normally unchecking the "Use Custom HTTP Body" so you can send a GET request?

**Comment by hellopatrick** [comment]
RESTed 2.5.2 will now simply ignore the Custom HTTP body when sending the GET request.  So, you'll no longer need to uncheck "Use Custom HTTP Body" when you want to send a GET request.

Thus you can just leave it set and switch back and forth between methods and the HTTP body will only be sent when it makes sense (i.e. not a known GET-like method).
