### ISSUE TITLE
Preview HTML

### ISSUE THREAD

**Issue by tom--** [helloresolven/rested#23]
Rested is really nice but I'm still using the DEV HTTP CLIENT extension for Chrome because it can display an HTML page if the server returns one.

The framework I use on the server side, Yii, when in debug mode, generates excellent HTML information pages when errors or exceptions are encountered. They are too hard to read in Rested. It would not be hard to preview HTML responses as HTML:

![DEV HTTP CLIENT](http://i.imgur.com/quq29.png)

**Comment by hellopatrick** [comment]
Will look into adding this to the next major update (3.0).

**Comment by hellopatrick** [comment]
Have received multiple more requests for this via e-mail, so yeah, this will be added in 3.0 in some form.

**Comment by tom--** [comment]
:)

**Comment by vchav73** [comment]
Just bought the app. Very good, but web page view would make it perfect for me. Would be good to have the option to do a preview in Reseted or launch a browser with the page that was returned by the request. Bonus points if you can select from the default or any installed browser.

**Comment by hellopatrick** [comment]
This will be added in RESTed 2.6...

![Screen Shot 2013-03-07 at 11 03 25 AM](https://f.cloud.github.com/assets/9581/232780/8e6065e6-8740-11e2-851d-b7330188d4f6.png)

![Screen Shot 2013-03-07 at 10 52 26 AM](https://f.cloud.github.com/assets/9581/232766/4dd9ba4a-8740-11e2-8ba2-0bff7eccb8c0.png)

Currently there's a link on the initial response that gives you the option to resend the request and view the rendered content.  I'm not happy currently with having to resend the request, but my initial attempts to just display the received data leads to lots of broken images/css.

**Comment by vchav73** [comment]
Awesome!! Looking forward to the 2.6 rev. Thanks!
