### ISSUE TITLE
More & Expanded Caption editing

### ISSUE THREAD

**Issue by callmetwain** [helloresolven/rested#28]
It sucks that you can only have one caption and there is very little editing to the caption you can do.  I'd like to see multiple captions plus a little more customization for the captions.

**Comment by hellopatrick** [comment]
Hi,

I'm assuming this is a feature request for GIF Brewery and not RESTed :)?

Anyways, multiple captions and overlays will be coming in the next major update for GIF Brewery (2.2).  I'm hoping they'll behave like layers in a photo editing application.

May I ask what customization you want for your captions?  I'm currently also working on a minor update for GIF Brewery (2.1.1) and it contains the ability to text-align the caption.  You may read more at http://gifbrewery.tumblr.com or download a beta version of it at http://www.helloresolven.com/betas/gifbrewery/.

The major thing I'm trying to decide now is how to best support the ability to have different captions show at different times.  That would allow captions to act truly as dialogue, which I'm sure is what people truly want.  (Also, I realize the caption is used by users as a watermark).

And just to keep GIF Brewery & RESTed separate, if you have future suggestions, feel free to send those via twitter (@[helloresolvapps](http://twitter.com/helloresolvapps)), tumblr (http://gifbrewery.tumblr.com/ask), or e-mail (contact at helloresolven dot com).

Thanks and have a good day,
Patrick
