### ISSUE TITLE
Always display a response body

### ISSUE THREAD

**Issue by Grimal** [helloresolven/rested#29]
I have a large number of REST APIs that return binary data - images, encrypted blobs, etc.  When calling APIs with RESTed, the body is displayed beautifully for common things - images, html, etc.  But if the content type is unexpected, nothing is displayed.  It would be very helpful if there were an option to display something, perhaps even the option for a hex dump, rather than nothing at all.

**Comment by hellopatrick** [comment]
I'll look into doing the hex dump option.  

When the response is received, I'll probably include a link in the response body that you may click before RESTed computes & displays a hex string.

**Comment by hellopatrick** [comment]
Here's a screenshot of RESTed displaying the hex string for just a simple JSON response.

![Screen Shot 2013-03-07 at 12 40 41 PM](https://f.cloud.github.com/assets/9581/233268/88ddbbba-874e-11e2-8101-72b192be31d2.png)

**Comment by Grimal** [comment]
That is outstanding.  Might seem simple, but that will really help!
