### ISSUE TITLE
Save response

### ISSUE THREAD

**Issue by erikreagan** [helloresolven/rested#3]
First let me say thank you for building this. I was on the hunt for a desktop-based app where I could easily save and test requests and this is great.

Any thoughts or plans on saving the response data — either header, body or both — to a .txt file or the response content-type (xml, json, etc)?

Cheers,
Erik

**Comment by hellopatrick** [comment]
Hi Erik,

No reason this can't be done.  I'll add it to the TODO for the next version.  

Perhaps on saving it'll provide a group of 3 checkboxes (request headers, response header, and response body), so you can choose on a case-by-case basis what you want to save..

-- Patrick

**Comment by erikreagan** [comment]
Sounds great. Thank you for the consideration.

Erik

**Comment by hellopatrick** [comment]
Added in 2.5, under `Request > Save Last Request & Response` in menu bar.

**Comment by erikreagan** [comment]
Great! I look forward to using the feature :)
