### ISSUE TITLE
Better Save Last Request & Response

### ISSUE THREAD

**Issue by emlama** [helloresolven/rested#30]
I love this functionality as I use RESTed to test and verify webservices that I haven't written. The last request and response is a great way to tell someone what I was trying to do and help diagnose what went wrong.

Unfortunately, as it stands it's missing the HTTP Method, URL and Response time and headers (request headers, request body, response headers, response body) for each section. Adding those in would make the report more usable.

Additionally, the request body and response headers need a line break between them. Currently I see this:

{
  "full_name": "Matt",
  "email": "foo@foobar.com",
}Content-Type: application/json

Thanks for all the good work, it's a great app :+1:

**Comment by hellopatrick** [comment]
The save last request & response should be improved in the RESTed 2.6. You can try a pre-release version of 2.6 at http://www.helloresolven.com/betas/rested/.

The only thing I've decided not to include is the response time.

![screen shot 2013-07-02 at 11 59 04 am](https://f.cloud.github.com/assets/9581/737500/6d0f17c4-e330-11e2-8636-22ffe43e5179.png)

**Comment by emlama** [comment]
Awesome thanks!
