### ISSUE TITLE
Format JSON in "Custom HTTP Body"

### ISSUE THREAD

**Issue by mattvague** [helloresolven/rested#31]
Would be a very nice touch if when you typed or pasted incorrectly formatted but valid JSON and sent a request that your JSON would automatically be formatted.

Typical use case:

Receive a support request with badly formatted example JSON that causes an error, paste it into RESTed and make request, analyze JSON for cause of problem. That last step would be made far easier if the JSON was always correctly formatted.

**Comment by hellopatrick** [comment]
Hmm, I could add an option such that if the Content-Type header is set to "application/json", RESTed would try to prettify the HTTP body string before sending.  

That way the HTTP request body would either be pretty in case of valid JSON or still a jumbled mess in-case of poorly formed JSON.

**Comment by mattvague** [comment]
Hmm, sounds good. Thanks for the quick response, love your app!
