### ISSUE TITLE
Set-cookie ignored on redirects.

### ISSUE THREAD

**Issue by SailingYYC** [helloresolven/rested#39]
When `Follow Redirects` is checked and the response issued is a redirect, **Rested** does not store the cookie as returned in the redirect response, and issue this updated cookie on the subsequent request.

**Comment by hellopatrick** [comment]
@SailingYYC, sorry for the delay in getting to this.  Would you mind testing the pre-release version of RESTed 2.6 at http://www.helloresolven.com/betas/rested/?

On my end, I've tested it (https://github.com/hellopatrick/rested/blob/master/servers/express.js) and it seems to send the cookie as desired.

A GET request to /cookie sets a 'name' cookie and redirects RESTed to /cookie-set.  
The server sees that cookie is indeed sent:

![screen shot 2013-07-02 at 11 52 20 am](https://f.cloud.github.com/assets/9581/737452/655d5bcc-e32f-11e2-8781-8571fa3e3eb6.png)

It may just be an issue of RESTed showing the original request, sans cookie, but the redirect request does get the cookie attached.

**Comment by SailingYYC** [comment]
Hey Patrick, no worries on the timeframe, RESTed is a great tool for adhoc testing.

It has been a while and while I'm pretty thorough before I submit an issue, the beta version works perfectly.

I may have to claim mia culpa on the bug submission, I've verified in my API logs that it is making the redirect request.  My auth handlers where this is used reject the POST verb on the entity, which is the verb required to auth on the collection and subsequently used by Rested for the redirect.

Thanks again for a great product!
