### ISSUE TITLE
Improve result screen

### ISSUE THREAD

**Issue by beny** [helloresolven/rested#4]
It would be really awesome to have better result screen. For example Request and Response header could be next to each other, and can be both collapsable. Most of the time I'm watching over the response body and now I have to scroll a lot on small screen.

**Comment by hellopatrick** [comment]
Thanks for the suggestion.  I don't know if I'll put them side-by-side, but I'll definitely look into collapsing them.

**Comment by hellopatrick** [comment]
I'm currently doing something like this for the next version:

![test layout](http://i.imgur.com/q9bmx.png)

You can click the "links" in the result screen to collapse that section.

**Comment by hellopatrick** [comment]
Complete with 2.5.
