### ISSUE TITLE
Support empty parameters

### ISSUE THREAD

**Issue by ideabucket** [helloresolven/rested#40]
At the moment, if in a GET request you specify:

> parameter1=foo
> parameter2=

i.e., a null value for a parameter, RESTed sends `GET /bar?parameter1=foo`. It would be good if you could supply empty parameters, so it would send `GET /bar?parameter1=foo&parameter2=`.

**Comment by hellopatrick** [comment]
This has been added in the next update, which will I'll be posting as pre-release version very soon.

**Comment by hellopatrick** [comment]
@ideabucket, I've updated the pre-release of RESTed at http://www.helloresolven.com/betas/rested/.  It should now respect empty parameters everywhere.

**Comment by ideabucket** [comment]
@hellopatrick Brilliant, thank you!
