### ISSUE TITLE
Request Headers & Body, Response Headers, and Response Body do not stay collapsed.

### ISSUE THREAD

**Issue by SailingYYC** [helloresolven/rested#41]
Hey Patrick, Loving the beta release, tightens a number of things up, particularly command-L working everywhere is a godsend!

Unfortunately I noticed on every request submission all 3 panels on the right expand.  In version 2.5.2 they retained their previous state on every request submission (on a per window basis).

When I'm debugging my API core, all I look at are headers, when I'm debugging my API's all I care about are the response body's, having the 3 panel states return to expanded on every request really slows this down.

If others have requested this, could we make it a configurable option?

Thanks again for all your work, best REST tool I've found on the Mac!

C.

**Comment by hellopatrick** [comment]
Hey,

I've updated the RESTed beta (http://www.helloresolven.com/betas/rested/) with this.
1. Things should now remember what was collapsed.
2. In RESTed's preferences, you can now select what will be shown by default.
