### ISSUE TITLE
Basic Auth seems not to work

### ISSUE THREAD

**Issue by tclaus** [helloresolven/rested#42]
I jut entered my url and got a "401 Unauthorized". response. Added under 'Authorization' my username (without password / empty password) and sent the request again. 
And I got again a 401 Unauthorized. 

Sending the same request from Safari works pretty well after entering my username. 

I can't see any BasicAuth - In the request header.  Is the header really send?

**Comment by hellopatrick** [comment]
RESTed 2.5 only sends the Authorization headers if the username and password field aren't empty.

I suppose this could changed for 2.6 update.

**Comment by tclaus** [comment]
Ah, OK. Can you fix this? 
My service provider has accounts without any password for testing purposes. I am using RESTed 2.5.2 and it is unusable for me.

**Comment by hellopatrick** [comment]
Yes, it'll be changed for RESTed 2.6.  I'll leave a note here when I update the RESTed 2.6 beta at http://helloresolven.com/betas/rested with this fix.

**Comment by hellopatrick** [comment]
Hi @vvanchesa , The RESTed 2.6 pre-release version has been updated with the change.  

You can get it at http://www.helloresolven.com/betas/rested/.  Tell me if that fixes the issue.

Thanks,
Patrick

**Comment by tclaus** [comment]
The current beta works well with empty passwords. (I tested it with basicAuth). Thank you.
Thorsten
