### ISSUE TITLE
[Bug] Crash after trying to request without URL

### ISSUE THREAD

**Issue by lukasbestle** [helloresolven/rested#44]
You can reproduce the crash like this:
1. Use any settings (params, body etc.)
2. Delete every character in the URL field so it is completely empty
3. Hit enter or "Send Request"
4. RESTed crashes instantly

If you need one, I can provide you with an error log by email. :)

**Comment by hellopatrick** [comment]
Should now be fixed in pre-release version of 2.7 at http://www.helloresolven.com/betas/rested/.
