### ISSUE TITLE
JSON encoding of true/false

### ISSUE THREAD

**Issue by ejeklint** [helloresolven/rested#46]
JSON-encoded parameters with value true or false gets converted to strings "true" or "false" and not the literals `true` or `false`. This is not proper JSON encoding and makes calling REST API:s which expects strict JSON a bit more cumbersome.

Workaround: Use Custom HTTP Body and edit away the quotes.

**Comment by hellopatrick** [comment]
Just fixed in pre-release version of 2.7, which is available at http://www.helloresolven.com/betas/rested/.

**Comment by ejeklint** [comment]
Sweet, works as expected now!
