### ISSUE TITLE
TLS 1.1 / 1.2

### ISSUE THREAD

**Issue by isdn** [helloresolven/rested#61]
Hello.

It seems that RESTed does not support https connections via TLS v. 1.1/1.2 (in the case that no other protocols are available).
I tried several sites and got the error "An SSL error has occurred and a secure connection to the server cannot be made.".
Servers which support at least TLS v.1.0 work fine.

Thanks.
Denis

**Comment by hellopatrick** [comment]
2.7.1 will fix this for Yosemite users.  2.7.1 is available as a pre-release at http://www.helloresolven.com/betas/rested/.

**Comment by isdn** [comment]
That is great, thank you!

**Comment by natemcintyre** [comment]
Is there any ETA on when you expect to have 2.7.1 released to the App Store?
