### ISSUE TITLE
Incorrect HTML nesting in Response Body

### ISSUE THREAD

**Issue by natesilva** [helloresolven/rested#7]
Hi,

I’m using Rested 2.3.

The “Pretty Print Output” feature tries to convert non-XML content into XML. This causes strange nesting errors—which had me very confused today!

My app outputs HTML5 (not XHTML). The problem happens when you use an HTML tag that doesn’t need a closing tag. Here’s a sample document:

```
<!DOCTYPE html>
<html>
<head>
    <title>Example</title>
</head>
<body>
    <form method="post">
        <input type="text">
    </form>
    <div>This goes after the form</div>
</body>
</html>
```

If you drop that on a web server and request it using Rested with the Pretty Print Output option, you’ll see that an `<?xml…>` header is added, and everything after the `<input>` tag is incorrectly nested.

Of course, if I was using _XHTML_, then I would have to close the input tag, but doing so is not required in HTML5 and prohibited in HTML 4.

The templating tools I’m using generate HTML5, non-XML, by default.

Regards,
Nate

**Comment by hellopatrick** [comment]
Hi,

Pretty-printing will be improved/fixed in RESTed 2.5 (the next version).  I've just tested your sample document in RESTed 2.5 and it pretty-prints as desired, no more errant XML garbage.

![test](http://i.imgur.com/RdC6A.png)

Thanks.

**Comment by natesilva** [comment]
That looks great. Can’t wait for the next version!

**Comment by hellopatrick** [comment]
HTML pretty-printing should now be much better in 2.5.
