### ISSUE TITLE
Header does not specific HTTP Version

### ISSUE THREAD

**Issue by dantetwc** [helloresolven/rested#8]
Hi,

Rested does not provide HTTP Header in request

This doesn't work

```
Request Header
GET /services/json
Accept-Encoding: gzip
User-Agent: Rested 2.3 (Macintosh; Mac OS X 10.8.0; en_HK)
```

This causes some server responded with null body

Work Version

```
GET /services/json HTTP/1.1
```

Please add feature that can let us choose the HTTP version

**Comment by hellopatrick** [comment]
1. I'll re-add the HTTP version.
2. There are currently no plans to support other HTTP versions (all there is 1.0?).

**Comment by mauricerkelly** [comment]
There is 0.9 as well, though how widely it is used I could not say.

**Comment by hellopatrick** [comment]
2.5 now shows that it is HTTP 1.1. This is the only supported HTTP version.
